### ISSUE TITLE
Wrong identation level

### ISSUE THREAD

**Issue by Starry03** [keyhr/vscode-42-c-format#9]
the line
"			mlx_put_image_to_window(window->mlx, window->window, window->bg_img, x, y);"
is formatted as 
"			mlx_put_image_to_window(window->mlx, window->window, window->bg_img,
					x, y);"
when it should be 
"			mlx_put_image_to_window(window->mlx, window->window, window->bg_img,
				x, y);"
from running norminette

**Comment by keyhr** [comment]
This VSCode extension serves solely as a provider for `c_formatter_42`,  so any formatting issues are related to the formatter itself. Since the `c_formatter_42` project is no longer actively maintained, you can try fixing it yourself.

BTW, what is the difference between the formatting result and the expected one?
